version: '3.8'

x-postgres-common:
  &postgres-common
  restart: always
  healthcheck:
    test: 'pg_isready -U user --dbname=postgres'
    interval: 10s
    timeout: 5s
    retries: 5

networks:
  database: {}

services:
  postgres_primary:
    <<: *postgres-common
    container_name: primary
    build:
      context: ./Master
      dockerfile: Dockerfile
    ports:
      - 5532:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_REPLICA_SYNC: my_custom_replica_sync
    volumes:
      - /var/lib/postgresql/docker/pg1:/var/lib/postgresql/data
    networks:
      - database

  postgres_async_replica:
    <<: *postgres-common
    container_name: async
    build:
      context: ./Replica
      dockerfile: Dockerfile
    depends_on:
      - postgres_primary
    volumes:
      - /var/lib/postgresql/docker/pg2:/var/lib/postgresql/data
    networks:
      - database

  postgres_sync_replica:
    <<: *postgres-common
    container_name: sync
    build:
      context: ./Replica
      dockerfile: Dockerfile
    depends_on:
      - postgres_primary
    volumes:
      - /var/lib/postgresql/docker/pg3:/var/lib/postgresql/data
    environment:
      - REPLICA_TYPE=sync
    networks:
      - database

  postgres_potential_replica:
    <<: *postgres-common
    container_name: pot
    build:
      context: ./Replica
      dockerfile: Dockerfile
    depends_on:
      - postgres_primary
    volumes:
      - /var/lib/postgresql/docker/pg4:/var/lib/postgresql/data
    environment:
      - REPLICA_TYPE=sync
    networks:
      - database
    
  # haproxy:
  #   container_name: haproxy
  #   build:
  #     context: ./haproxy
  #     dockerfile: Dockerfile
  #   ports:
  #     - 5533:5432
  #   networks:
  #     - database
  #   depends_on:
  #     - postgres_primary
  #     - postgres_async_replica
  #     - postgres_sync_replica
  #     - postgres_potential_replica

  
  # barman_active_backup:
  #   image: ubcctlt/barman
  #   depends_on:
  #     - postgres_primary
  #   networks:
  #     - database
  #   environment:
  #     - DB_HOST=postgres_primary 
  #     - DB_PORT=5432 
  #     - DB_SUPERUSER=user 
  #     - DB_SUPERUSER_PASSWORD=123 
  #     - DB_SUPERUSER_DATABASE=postgres 
  #     - DB_REPLICATION_USER=barman_streamer 
  #     - DB_REPLICATION_PASSWORD=bs123 
  #     - DB_SLOT_NAME=barman_slot 
  #     - DB_BACKUP_METHOD=postgres 

