apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_USER: "user"
  POSTGRES_DB: "postgres"
  POSTGRES_PASSWORD: "123"
  POSTGRES_REPLICA_SYNC: "my_custom_replica_sync"
  REPLICA_TYPE: "sync"
  MASTER_HOST: "postgres-primary"
  MASTER_PORT: "5432"
  REPLICATION_USER : "replicator"
  REPLICATION_PASS: "123456"
  NUMBER_SYNC_DB: "1"
  MAX_REPLICATION_SLOTS: "10"
  MAX_WAL_SENDERS: "10"
