apiVersion: v1
kind: Service
metadata:
  name: patronidemo-replica
  labels:
    application: patroni
    cluster-name:  &cluster_name patronidemo
    role: replica
spec:
  type: ClusterIP
  selector:
    application: patroni
    cluster-name: *cluster_name
    role: replica
  ports:
  - name: pg
    port: 5432
    targetPort: 5432
  - name: patroni
    port: 8008
    targetPort: 8008
---
apiVersion: v1
kind: Service
metadata:
  name: patronidemo-master
  labels:
    application: patroni
    cluster-name:  &cluster_name patronidemo
    role: primary
spec:
  type: ClusterIP
  selector:
    application: patroni
    cluster-name: *cluster_name
    role: primary
  ports:
    - name: pg
      port: 5432
      targetPort: 5432
    - name: patroni
      port: 8008
      targetPort: 8008
---