apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-primary
spec:
  serviceName: "postgres-primary"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-primary
  template:
    metadata:
      labels:
        app: postgres-primary
    spec:
      containers:
        - name: dbaas-postgres-primary
          image: dbaas-postgres_primary:latest
          imagePullPolicy: Never  # Force Kubernetes to use the locally loaded image
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: postgres-storage
          livenessProbe: 
            exec: 
              command: 
                - /bin/sh
                - -c
                - pg_isready -h 127.0.0.1 -p 5432 -q
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 1
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-primary-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-primary
spec:
  selector:
    app: postgres-primary
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
