apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-replicas
spec:
  serviceName: "postgres-replicas"
  replicas: 3
  selector:
    matchLabels:
      app: postgres-replica
  template:
    metadata:
      labels:
        app: postgres-replica
    spec:
      containers:
        - name: dbaas-postgres-sync-replica
          image: dbaas-postgres_sync_replica:latest
          imagePullPolicy: Never  # Force Kubernetes to use the locally loaded image
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: postgres-storage
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  result=$(PGPASSWORD="123" psql -h 127.0.0.1 -U user -d postgres -t -A -c "select count(*) from pg_stat_wal_receiver;" 2>/dev/null)
                  if [ $? -ne 0 ] || [ "$result" -eq 0 ]; then
                    exit 1
                  fi
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 1
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-replica-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-replicas
spec:
  selector:
    app: postgres-replica
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
