apiVersion: v1
kind: Secret
type: Opaque
metadata:
 name: pgadmin
stringData:
  pgadmin-password: {{.Values.pgadmin.pass}}
---
apiVersion: v1
kind: ConfigMap
metadata:
 name: pgadmin-config
data:
 servers.json: |
   {
       "Servers": {
         "1": {
           "Name": "PostgreSQL DB Master",
           "Group": "Servers",
           "Port": 5432,
           "Username": "postgres",
           "Host": "patronimvp-master-{{ .Values.patroniReleaseName }}",
           "SSLMode": "prefer",
           "MaintenanceDB": "postgres"
         },
         "2": {
           "Name": "PostgreSQL DB Replica",
           "Group": "Servers",
           "Port": 5432,
           "Username": "postgres",
           "Host": "patronimvp-master-{{ .Values.patroniReleaseName }}",
           "SSLMode": "prefer",
           "MaintenanceDB": "postgres"
         },
         "3": {
           "Name": "PostgreSQL DB Pgcat",
           "Group": "Servers",
           "Port": 5432,
           "Username": "postgres",
           "Host": "{{ .Release.Name }}-proxy-service",
           "SSLMode": "prefer",
           "MaintenanceDB": "postgres"
         }
       }
   }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pgadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: {{.Values.pgadmin.email}}
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin
                  key: pgadmin-password
          volumeMounts:
          - name: pgadmin-config
            mountPath: /pgadmin4/servers.json
            subPath: servers.json
            readOnly: true
      volumes:
      - name: pgadmin-config
        configMap:
          name: pgadmin-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pgadmin-service
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name:  {{ .Release.Name }}-pgadmin
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`pgadmin.dbaas.site`)
    kind: Rule
    services:
    - name:  {{ .Release.Name }}-pgadmin-service
      port: 80
