apiVersion: v1
kind: ConfigMap
metadata:
  name: pgcat-config
data:
  pgcat.yaml: |
    general:
      PGCAT_PORT: '5432'
      PGCAT_SUPERUSER_USERNAME: postgres
      PGCAT_SUPERUSER_PASSWORD: mmm
      ENABLE_PROMETHEUS: true
      PROMETHEUS_EXPORTER_PORT: 9930
    DBS:
      - NAME: postgres
        POOL_MODE: session
        PRIMARY_READ: false
        SHARDING_FUNCTION: pg_bigint_hash
        users:
          - USER_NAME: postgres
            PASSWORD: mmm
            POOL_SIZE: 9
            STATEMENT_TIMEOUT: 0
        shards:
          - MASTER_HOST: patronimvp-master-{{ .Values.patroniReleaseName }}
            MASTER_PORT: '5432'
            REPLICA_HOST: patronimvp-replica-{{ .Values.patroniReleaseName }}
            REPLICA_PORT: '5432'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-proxy-deployment
  labels:
    app: proxy
    release-name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy
          image: {{ .Values.pgcatImageName }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.pgcatConf.pgcatPort }}
              protocol: TCP
          volumeMounts:
            - name: pgcat-data
              mountPath: /etc/pgcat
        - name: pgcat-config-watcher
          image: {{ .Values.pgcatConfigWatcherImageName }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: PGCAT_CONFIG_SOURCE
              value: "/config/pgcat.yaml"
            - name: PGCAT_CONFIG_DEST
              value: "/etc/pgcat/pgcat.toml"
          volumeMounts:
            - name: pgcat-config
              mountPath: /config  # Read-only source
              readOnly: true
            - name: pgcat-data
              mountPath: /etc/pgcat # Writable target
      volumes:
        - name: pgcat-config
          configMap:
            name: pgcat-config
            items:
              - key: pgcat.yaml
                path: pgcat.yaml
        - name: pgcat-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-proxy-service
  labels:
    app: proxy
    release-name: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
    - name: pgcat
      port: 5432
      targetPort: {{ .Values.pgcatConf.pgcatPort }}
      protocol: TCP
      nodePort: 30432  # must be between 30000–32767
  selector:
    app: proxy


