replicaCount: 1
imagePullPolicy: IfNotPresent
pgcatImageName: ghcr.io/postgresml/pgcat:v1.2.0
pgcatConfigWatcherImageName: dbaas/pgcat-config-watcher:1.1.1
patroniReleaseName: patroni-mvp
pgcatconfig:
  general:
    PGCAT_PORT: '5432'
    PGCAT_SUPERUSER_USERNAME: postgres
    PGCAT_SUPERUSER_PASSWORD: ''
    ENABLE_PROMETHEUS: true
    PROMETHEUS_EXPORTER_PORT: 9930
  DBS:
  - NAME: postgres
    POOL_MODE: session
    PRIMARY_READ: false
    SHARDING_FUNCTION: pg_bigint_hash
    users:
    - USER_NAME: postgres
      PASSWORD: ''
      POOL_SIZE: 9
      STATEMENT_TIMEOUT: 0
    shards:
    - MASTER_HOST: ''
      MASTER_PORT: '5432'
      REPLICA_HOST: ''
      REPLICA_PORT: '5432'
pgadmin:
  email: admin@example.com
  pass: ''
  existingSecret: ''
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits: {}
  scheduling:
    antiAffinity: none
    topologyKey: kubernetes.io/hostname
    nodeSelector: &id001 {}
    tolerations: &id002 []
    affinity: &id003 {}
    topologySpreadConstraints: &id004 []
pgadminIngress:
  enabled: false
  host: ''
security:
  allowInlineSecrets: false
existingSecret: ''
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits: {}
watcherResources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits: {}
scheduling:
  antiAffinity: preferred
  topologyKey: kubernetes.io/hostname
  nodeSelector: *id001
  tolerations: *id002
  affinity: *id003
  topologySpreadConstraints: *id004
terminationGracePeriodSeconds: 90
pdb:
  enabled: true
networkPolicy:
  enabled: false
  ingress: []
  egress: []
