minio: 
  replicaCount: 1
  imageName: docker push afzalzademohammad/minio:1.0.0 #quay.io/minio/minio
  mcImageName: docker.arvancloud.ir/afzalzademohammad/minio-mc:1.0.0
  imagePullPolicy: IfNotPresent
  rootUser: root
  rootPasword: 'adminadmin123'
  storageCapacity: 5Gi
  storageClass: standard
  consolePort: 9001
  adminPort: 9000
minioInit: 
  backupUser: mamamd
  backupPassword: 'adminadmin123'
  backupBucketName: backup

