replicaCount: 1
imagePullPolicy: IfNotPresent
pgcatImageName: ghcr.io/postgresml/pgcat
pgcatConfigWatcherImageName: docker.arvancloud.ir/afzalzademohammad/pgcat-config-watcher:1.0.0
patroniReleaseName: patroni-mvp
pgcatConf: 
  pgcatPort: 5432
  superuserUsername: postgres
  superuserPassword: mmm
  enablePrometheus: true
  prometheusExporterPort: 9930
  db:
    name: postgres
    poolMode: session
    primaryRead: false
pgadmin:
  email: mohammad.afzalzadeh.3@gmail.com
  pass: mmm
