apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pgadmin
  namespace: dbaas
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`pgadmin.dbaas.site`)
    kind: Rule
    services:
    - name: pgadmin-service
      port: 80
