apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-minio-credentials
type: Opaque
stringData:
  root-user: {{ .Values.minio.rootUser | quote }}
  root-password: {{ .Values.minio.rootPassword | quote }}
  backup-user: {{ .Values.minioInit.backupUser | quote }}
  backup-password: {{ .Values.minioInit.backupPassword | quote }}
  backup-bucket: {{ .Values.minioInit.backupBucketName | quote }}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-minio-statefulset
spec:
  serviceName: minio
  replicas: {{ .Values.minio.replicaCount }}
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: minio
        image: {{ .Values.minio.imageName }}
        imagePullPolicy: {{ .Values.minio.imagePullPolicy }}
        args:
          - server
          - /data
          - --console-address
          - ":{{ .Values.minio.consolePort }}"
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-minio-credentials
              key: root-user
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-minio-credentials
              key: root-password
        - name: MINIO_PROMETHEUS_AUTH_TYPE
          value: "public"
        ports:
        - containerPort: {{ .Values.minio.adminPort }}
        - containerPort: {{ .Values.minio.consolePort }}
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        application: minio
      annotations:
          volume.alpha.kubernetes.io/storage-class: {{ .Values.minio.storageClass }}
    spec:
      storageClassName: {{ .Values.minio.storageClass }}
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.minio.storageCapacity }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-minio
  labels:
    app: minio
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ports:
  - port: 9000
    name: api
  - port: 9001
    name: console
  clusterIP: None
  selector:
    app: minio
    app.kubernetes.io/instance: {{ .Release.Name }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-init-minio-scripts
data:
  init-minio.sh: |
    #!/bin/sh
    set -e

    # Set mc alias
    mc alias set myminio http://{{ .Release.Name }}-minio:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD"

    # Create new user
    if ! mc admin user info myminio "$MINIO_BACKUP_USER" >/dev/null 2>&1; then
      mc admin user add myminio "$MINIO_BACKUP_USER" "$MINIO_BACKUP_PASSWORD"
    fi

    # Create bucket
    mc mb "myminio/$MINIO_BACKUP_BUCKET" --ignore-existing

    # Attach readwrite policy to user
    mc admin policy attach myminio readwrite --user "$MINIO_BACKUP_USER"

    echo "✅ MinIO setup complete"

---

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-init-minio-job
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: init-minio
        image: {{ .Values.minio.mcImageName }}
        command: ["/bin/sh", "-c"]
        args:
          - sh /scripts/init-minio.sh
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-minio-credentials
              key: root-user
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-minio-credentials
              key: root-password
        - name: MINIO_BACKUP_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-minio-credentials
              key: backup-user
        - name: MINIO_BACKUP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-minio-credentials
              key: backup-password
        - name: MINIO_BACKUP_BUCKET
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-minio-credentials
              key: backup-bucket
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
      restartPolicy: OnFailure
      volumes:
      - name: script-volume
        configMap:
          name: {{ .Release.Name }}-init-minio-scripts

