apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rawfile-localpv
provisioner: local.openebs.io
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: true
parameters:
  storageType: hostpath
  BasePath: /var/local/openebs
