apiVersion: v1
kind: ServiceAccount
metadata:
  name: dbaas-backend
  namespace: dbaas
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dbaas-backend-helm
  namespace: dbaas
rules:
  - apiGroups: [""]
    resources: ["configmaps","secrets","services","persistentvolumeclaims","pods"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: ["apps"]
    resources: ["deployments","statefulsets","daemonsets","replicasets"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: ["batch"]
    resources: ["jobs","cronjobs"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get","list","watch","create","update","patch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dbaas-backend-helm
  namespace: dbaas
subjects:
  - kind: ServiceAccount
    name: dbaas-backend
    namespace: dbaas
roleRef:
  kind: Role
  name: dbaas-backend-helm
  apiGroup: rbac.authorization.k8s.io
