apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: patroni
  namespace: monitoring
  labels:
    release: kube-prometheus-stack   # must match your Prometheus release name
spec:
  selector:
    matchLabels:
      application: patroni
      type: monitoring
      monitoring-role: member
  namespaceSelector:
    matchNames:
      - dbaas
  endpoints:
    - port: patroni
      interval: 30s
      path: /metrics
